id: 3b3c613ecf8d40a4a37f5542861b0816
initial_creation_type: ocr
source_metadata:
  volumes:
    4dd9dda40b5d4aa59944e98fde4a00a4:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་མའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
